server:
  port: 8010
spring:
  application:
    name: mmb-eureka-server
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #表示是否注册自身到eureka服务器 因为当前应用就是eureka服务器 所以false
    fetch-registry: false #表示是否从服务器获取注册信息 同上
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置服务器所在地址 查询和注册服务都需要依赖这个地址



#server.port=8761
#eureka.instance.hostname=localhost
#eureka.client.registerWithEureka=false
#eureka.client.fetchRegistry=false
#eureka.client.serviceUrl.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/
#spring.application.name=mmb-eureka-server